In [1]:
import pandas as pd
# pylint: disable=import-error disable=wrong-import-position
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath("__file__"))))

print(os.path.dirname(os.path.abspath("__file__")))
import pydit
df=pd.read_excel("./demo_data/demo_data.xlsx")

/Users/juanespasandin/github/pydit/examples

In [6]:
pydit.check_blanks(df)

,Auth_ID,Date Authorisation,Cust ID,Amount,Date Procedure,Region,Vulnerable,Notes,Auth_ID_blanks,Date Authorisation_blanks,Cust ID_blanks,Amount_blanks,Date Procedure_blanks,Region_blanks,Vulnerable_blanks,Notes_blanks,has_blanks
0,9000001,2020-05-19 10:24:41.740,3710,9.11,2020-06-12 10:24:41.740,London,False,"Test of delimiter, this should be kept all tog...",False,False,False,False,False,False,False,False,False
1,9000002,2020-05-19 11:49:24.093,3378,11.65,2020-07-21 11:49:24.093,West,False,NaN,False,False,False,False,False,False,False,True,True
2,9000003,2020-05-19 13:09:24.093,1963,13.52,2020-06-21 13:09:24.093,West,False,NaN,False,False,False,False,False,False,False,True,True
3,9000004,2020-05-19 13:40:02.391,3565,77.57,2020-05-23 13:40:02.391,East,False,NaN,False,False,False,False,False,False,False,True,True
4,9000005,2020-05-19 15:00:02.391,2249,21.37,2020-07-26 15:00:02.391,East,False,Customer may be vulnerable,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1703,9001701,2020-08-14 08:20:44.652,2212,37.38,NaT,East,False,NaN,False,False,False,False,True,False,False,True,True
1704,9001702,2020-08-14 09:56:44.652,1187,-7.79,NaT,London,False,NaN,False,False,False,False,True,False,False,True,True
1705,9001703,2020-08-14 10:59:21.173,2076,-13.82,NaT,East,False,NaN,False,False,False,False,True,False,False,True,True
1706,9001704,2020-08-14 12:07:55.459,2380,39.62,NaT,West,False,NaN,False,False,False,False,True,False,False,True,True
1707,9001705,2020-08-14 13:03:18.536,3980,10.56,2020-08-30 13:03:18.536,South,False,NaN,False,False,False,False,False,False,False,True,True

In [5]:
dfr[dfr["Region_blanks"]]
dfr.head()

,Auth_ID,Date Authorisation,Cust ID,Amount,Date Procedure,Region,Vulnerable,Notes,Auth_ID_blanks,Date Authorisation_blanks,Cust ID_blanks,Amount_blanks,Date Procedure_blanks,Region_blanks,Vulnerable_blanks,Notes_blanks,has_blanks
0,9000001,2020-05-19 10:24:41.740,3710,9.11,2020-06-12 10:24:41.740,London,False,"Test of delimiter, this should be kept all tog...",False,False,False,False,False,False,False,False,False
1,9000002,2020-05-19 11:49:24.093,3378,11.65,2020-07-21 11:49:24.093,West,False,NaN,False,False,False,False,False,False,False,True,True
2,9000003,2020-05-19 13:09:24.093,1963,13.52,2020-06-21 13:09:24.093,West,False,NaN,False,False,False,False,False,False,False,True,True
3,9000004,2020-05-19 13:40:02.391,3565,77.57,2020-05-23 13:40:02.391,East,False,NaN,False,False,False,False,False,False,False,True,True
4,9000005,2020-05-19 15:00:02.391,2249,21.37,2020-07-26 15:00:02.391,East,False,Customer may be vulnerable,False,False,False,False,False,False,False,False,False

In [ ]:

df["Region"+ "_strip"] = df["Region"].fillna("").astype(str).str.strip()
            
df[df["Region_strip"]==""]

In [ ]:
df["Region_blanks"] = ~df["Region_strip"].astype(bool)

In [ ]:
df[df["Region_blanks"]==True]
df.head()